# Generated by Django 6.0.6 on 2026-06-15 20:09

import core.models
import django.contrib.postgres.indexes
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalStudent",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("full_name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                ("nationality", models.CharField(max_length=100)),
                ("highest_qualification", models.CharField(max_length=100)),
                ("institution_name", models.CharField(max_length=200)),
                ("graduation_year", models.PositiveSmallIntegerField()),
                ("gpa", models.DecimalField(decimal_places=2, max_digits=4)),
                (
                    "gpa_scale",
                    models.DecimalField(decimal_places=1, default=4.0, max_digits=3),
                ),
                (
                    "normalized_gpa_4",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=3, null=True
                    ),
                ),
                ("backlogs", models.PositiveSmallIntegerField(default=0)),
                ("gap_years", models.PositiveSmallIntegerField(default=0)),
                (
                    "ielts_overall",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=2, null=True
                    ),
                ),
                (
                    "ielts_listening",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=2, null=True
                    ),
                ),
                (
                    "ielts_reading",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=2, null=True
                    ),
                ),
                (
                    "ielts_writing",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=2, null=True
                    ),
                ),
                (
                    "ielts_speaking",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=2, null=True
                    ),
                ),
                ("ielts_trf_number", models.CharField(blank=True, max_length=20)),
                ("ielts_test_date", models.DateField(blank=True, null=True)),
                (
                    "available_funds_usd",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "funds_held_days",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("preferred_countries", models.JSONField(default=list)),
                (
                    "preferred_intake_month",
                    models.CharField(
                        choices=[
                            ("January", "January"),
                            ("February", "February"),
                            ("March", "March"),
                            ("April", "April"),
                            ("May", "May"),
                            ("June", "June"),
                            ("July", "July"),
                            ("August", "August"),
                            ("September", "September"),
                            ("October", "October"),
                            ("November", "November"),
                            ("December", "December"),
                        ],
                        max_length=20,
                    ),
                ),
                ("preferred_intake_year", models.PositiveSmallIntegerField()),
                ("max_budget_usd", models.PositiveIntegerField(blank=True, null=True)),
                ("scholarship_priority", models.PositiveSmallIntegerField(default=3)),
                ("ranking_priority", models.PositiveSmallIntegerField(default=3)),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("lead", "New Lead"),
                            ("docs_pending", "Documents Pending"),
                            ("profile_ready", "Profile Ready"),
                            ("shortlisted", "University Shortlisted"),
                            ("applied", "Applications Submitted"),
                            ("offer_received", "Offer Received"),
                            ("visa_applied", "Visa Applied"),
                            ("visa_granted", "Visa Granted"),
                            ("visa_refused", "Visa Refused"),
                        ],
                        default="lead",
                        max_length=20,
                    ),
                ),
                ("consent_storage", models.BooleanField(default=False)),
                ("consent_matching", models.BooleanField(default=False)),
                ("consent_communication", models.BooleanField(default=False)),
                ("consent_documents", models.BooleanField(default=False)),
                ("consent_timestamp", models.DateTimeField(blank=True, null=True)),
                ("consent_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "assigned_consultant",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical student",
                "verbose_name_plural": "historical students",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalUniversity",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("country", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("website", models.URLField()),
                ("program_name", models.CharField(max_length=200)),
                ("degree_level", models.CharField(max_length=50)),
                ("duration_months", models.PositiveSmallIntegerField()),
                ("tuition_usd", models.PositiveIntegerField()),
                ("intake_months", models.JSONField(default=list)),
                (
                    "min_ielts",
                    models.DecimalField(decimal_places=1, default=6.0, max_digits=2),
                ),
                (
                    "min_gpa_4",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=3, null=True
                    ),
                ),
                ("accepts_backlogs", models.BooleanField(default=True)),
                ("max_gap_years", models.PositiveSmallIntegerField(default=5)),
                ("requires_gre", models.BooleanField(default=False)),
                ("requires_work_exp", models.BooleanField(default=False)),
                ("work_exp_months", models.PositiveSmallIntegerField(default=0)),
                ("min_funds_usd", models.PositiveIntegerField()),
                (
                    "funds_held_days_required",
                    models.PositiveSmallIntegerField(default=28),
                ),
                ("ranking_qs", models.PositiveIntegerField(blank=True, null=True)),
                ("accreditation", models.CharField(blank=True, max_length=200)),
                ("last_verified_date", models.DateField()),
                ("data_source", models.CharField(default="manual", max_length=50)),
                ("is_active", models.BooleanField(default=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical university",
                "verbose_name_plural": "historical universitys",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                ("nationality", models.CharField(max_length=100)),
                ("highest_qualification", models.CharField(max_length=100)),
                ("institution_name", models.CharField(max_length=200)),
                ("graduation_year", models.PositiveSmallIntegerField()),
                ("gpa", models.DecimalField(decimal_places=2, max_digits=4)),
                (
                    "gpa_scale",
                    models.DecimalField(decimal_places=1, default=4.0, max_digits=3),
                ),
                (
                    "normalized_gpa_4",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=3, null=True
                    ),
                ),
                ("backlogs", models.PositiveSmallIntegerField(default=0)),
                ("gap_years", models.PositiveSmallIntegerField(default=0)),
                (
                    "ielts_overall",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=2, null=True
                    ),
                ),
                (
                    "ielts_listening",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=2, null=True
                    ),
                ),
                (
                    "ielts_reading",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=2, null=True
                    ),
                ),
                (
                    "ielts_writing",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=2, null=True
                    ),
                ),
                (
                    "ielts_speaking",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=2, null=True
                    ),
                ),
                ("ielts_trf_number", models.CharField(blank=True, max_length=20)),
                ("ielts_test_date", models.DateField(blank=True, null=True)),
                (
                    "available_funds_usd",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "funds_held_days",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("preferred_countries", models.JSONField(default=list)),
                (
                    "preferred_intake_month",
                    models.CharField(
                        choices=[
                            ("January", "January"),
                            ("February", "February"),
                            ("March", "March"),
                            ("April", "April"),
                            ("May", "May"),
                            ("June", "June"),
                            ("July", "July"),
                            ("August", "August"),
                            ("September", "September"),
                            ("October", "October"),
                            ("November", "November"),
                            ("December", "December"),
                        ],
                        max_length=20,
                    ),
                ),
                ("preferred_intake_year", models.PositiveSmallIntegerField()),
                ("max_budget_usd", models.PositiveIntegerField(blank=True, null=True)),
                ("scholarship_priority", models.PositiveSmallIntegerField(default=3)),
                ("ranking_priority", models.PositiveSmallIntegerField(default=3)),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("lead", "New Lead"),
                            ("docs_pending", "Documents Pending"),
                            ("profile_ready", "Profile Ready"),
                            ("shortlisted", "University Shortlisted"),
                            ("applied", "Applications Submitted"),
                            ("offer_received", "Offer Received"),
                            ("visa_applied", "Visa Applied"),
                            ("visa_granted", "Visa Granted"),
                            ("visa_refused", "Visa Refused"),
                        ],
                        default="lead",
                        max_length=20,
                    ),
                ),
                ("consent_storage", models.BooleanField(default=False)),
                ("consent_matching", models.BooleanField(default=False)),
                ("consent_communication", models.BooleanField(default=False)),
                ("consent_documents", models.BooleanField(default=False)),
                ("consent_timestamp", models.DateTimeField(blank=True, null=True)),
                ("consent_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_consultant",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HistoricalDocument",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("passport", "Passport"),
                            ("transcript", "Academic Transcript"),
                            ("ielts", "IELTS Scorecard"),
                            ("bank_statement", "Bank Statement"),
                            ("sop", "Statement of Purpose"),
                            ("lor", "Letter of Recommendation"),
                            ("resume", "Resume/CV"),
                            ("offer_letter", "University Offer Letter"),
                            ("visa_doc", "Visa Document"),
                        ],
                        max_length=20,
                    ),
                ),
                ("file", models.TextField(max_length=100)),
                ("uploaded_at", models.DateTimeField(blank=True, editable=False)),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("verified", "Verified Authentic"),
                            ("suspicious", "Suspicious — Request Original"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("review_notes", models.TextField(blank=True)),
                ("file_size_kb", models.PositiveIntegerField(blank=True, null=True)),
                ("file_extension", models.CharField(blank=True, max_length=10)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical document",
                "verbose_name_plural": "historical documents",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("passport", "Passport"),
                            ("transcript", "Academic Transcript"),
                            ("ielts", "IELTS Scorecard"),
                            ("bank_statement", "Bank Statement"),
                            ("sop", "Statement of Purpose"),
                            ("lor", "Letter of Recommendation"),
                            ("resume", "Resume/CV"),
                            ("offer_letter", "University Offer Letter"),
                            ("visa_doc", "Visa Document"),
                        ],
                        max_length=20,
                    ),
                ),
                ("file", models.FileField(upload_to=core.models.document_path)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("verified", "Verified Authentic"),
                            ("suspicious", "Suspicious — Request Original"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("review_notes", models.TextField(blank=True)),
                ("file_size_kb", models.PositiveIntegerField(blank=True, null=True)),
                ("file_extension", models.CharField(blank=True, max_length=10)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="core.student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="University",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("country", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("website", models.URLField()),
                ("program_name", models.CharField(max_length=200)),
                ("degree_level", models.CharField(max_length=50)),
                ("duration_months", models.PositiveSmallIntegerField()),
                ("tuition_usd", models.PositiveIntegerField()),
                ("intake_months", models.JSONField(default=list)),
                (
                    "min_ielts",
                    models.DecimalField(decimal_places=1, default=6.0, max_digits=2),
                ),
                (
                    "min_gpa_4",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=3, null=True
                    ),
                ),
                ("accepts_backlogs", models.BooleanField(default=True)),
                ("max_gap_years", models.PositiveSmallIntegerField(default=5)),
                ("requires_gre", models.BooleanField(default=False)),
                ("requires_work_exp", models.BooleanField(default=False)),
                ("work_exp_months", models.PositiveSmallIntegerField(default=0)),
                ("min_funds_usd", models.PositiveIntegerField()),
                (
                    "funds_held_days_required",
                    models.PositiveSmallIntegerField(default=28),
                ),
                ("ranking_qs", models.PositiveIntegerField(blank=True, null=True)),
                ("accreditation", models.CharField(blank=True, max_length=200)),
                ("last_verified_date", models.DateField()),
                ("data_source", models.CharField(default="manual", max_length=50)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["country", "is_active"],
                        name="core_univer_country_4c3a85_idx",
                    ),
                    models.Index(
                        fields=["min_ielts", "tuition_usd"],
                        name="core_univer_min_iel_cc655b_idx",
                    ),
                    models.Index(
                        fields=["degree_level"], name="core_univer_degree__1ea3fe_idx"
                    ),
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["intake_months"], name="core_univer_intake__a3a430_gin"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="MatchResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_eligible", models.BooleanField()),
                ("ineligible_reasons", models.JSONField(default=list)),
                ("preference_score", models.PositiveSmallIntegerField(default=0)),
                ("score_breakdown", models.JSONField(default=dict)),
                ("consultant_shortlisted", models.BooleanField(blank=True, null=True)),
                ("consultant_rejected", models.BooleanField(blank=True, null=True)),
                ("consultant_notes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches",
                        to="core.student",
                    ),
                ),
                (
                    "university",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.university",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HistoricalMatchResult",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("is_eligible", models.BooleanField()),
                ("ineligible_reasons", models.JSONField(default=list)),
                ("preference_score", models.PositiveSmallIntegerField(default=0)),
                ("score_breakdown", models.JSONField(default=dict)),
                ("consultant_shortlisted", models.BooleanField(blank=True, null=True)),
                ("consultant_rejected", models.BooleanField(blank=True, null=True)),
                ("consultant_notes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.student",
                    ),
                ),
                (
                    "university",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.university",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical match result",
                "verbose_name_plural": "historical match results",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["stage", "assigned_consultant"],
                name="core_studen_stage_ec5a19_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["preferred_intake_month", "preferred_intake_year"],
                name="core_studen_preferr_2bc9c1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["nationality"], name="core_studen_nationa_a978fd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["student", "doc_type", "review_status"],
                name="core_docume_student_0e0dde_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="matchresult",
            index=models.Index(
                fields=["student", "is_active", "preference_score"],
                name="core_matchr_student_915136_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="matchresult",
            unique_together={("student", "university")},
        ),
    ]
