# Generated by Django 5.2.15 on 2026-06-16 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_historicaluniversity_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalstudent',
            name='email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
