# Generated by Django 5.2.15 on 2026-06-16 21:42

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_historicalstudent_email_alter_student_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalDocumentUpload',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('passport', 'Passport'), ('transcript', 'Academic Transcript'), ('ielts', 'IELTS Scorecard'), ('combined', 'Combined Documents')], max_length=20)),
                ('file', models.TextField(max_length=100)),
                ('uploaded_at', models.DateTimeField(blank=True, editable=False)),
                ('extracted_data', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending Processing'), ('processing', 'Processing'), ('review', 'Ready for Review'), ('confirmed', 'Confirmed & Imported'), ('failed', 'Processing Failed')], default='pending', max_length=20)),
                ('processing_error', models.TextField(blank=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('parsed_student', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.student')),
                ('uploaded_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical document upload',
                'verbose_name_plural': 'historical document uploads',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='DocumentUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('passport', 'Passport'), ('transcript', 'Academic Transcript'), ('ielts', 'IELTS Scorecard'), ('combined', 'Combined Documents')], max_length=20)),
                ('file', models.FileField(upload_to='document_uploads/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('extracted_data', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending Processing'), ('processing', 'Processing'), ('review', 'Ready for Review'), ('confirmed', 'Confirmed & Imported'), ('failed', 'Processing Failed')], default='pending', max_length=20)),
                ('processing_error', models.TextField(blank=True)),
                ('parsed_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_uploads', to='core.student')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'doc_type'], name='core_docume_status_8d0af3_idx'), models.Index(fields=['uploaded_by', 'status'], name='core_docume_uploade_4e6bfd_idx')],
            },
        ),
    ]
