# Generated by Django 5.2.15 on 2026-06-17 01:58

import django.db.models.deletion
import simple_history.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_historicalcountry_history_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalstudent',
            name='preferred_countries',
        ),
        migrations.AlterField(
            model_name='historicalstudent',
            name='ielts_listening',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='historicalstudent',
            name='ielts_overall',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='historicalstudent',
            name='ielts_reading',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='historicalstudent',
            name='ielts_speaking',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='historicalstudent',
            name='ielts_writing',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='historicaluniversity',
            name='min_ielts',
            field=models.DecimalField(decimal_places=1, default=6.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='student',
            name='ielts_listening',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='ielts_overall',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='ielts_reading',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='ielts_speaking',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='ielts_writing',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='preferred_countries',
            field=models.ManyToManyField(blank=True, help_text='Select countries where the student wants to study', related_name='students_preferred', to='core.country'),
        ),
        migrations.AlterField(
            model_name='university',
            name='country',
            field=models.ForeignKey(blank=True, help_text='Select the country where the university is located', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='universities', to='core.country'),
        ),
        migrations.AlterField(
            model_name='university',
            name='min_ielts',
            field=models.DecimalField(decimal_places=1, default=6.0, max_digits=3),
        ),
        migrations.CreateModel(
            name='HistoricalStudent_preferred_countries',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('m2m_history_id', models.AutoField(primary_key=True, serialize=False)),
                ('country', models.ForeignKey(blank=True, db_constraint=False, db_tablespace='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.country')),
                ('history', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='core.historicalstudent')),
                ('student', models.ForeignKey(blank=True, db_constraint=False, db_tablespace='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.student')),
            ],
            options={
                'verbose_name': 'HistoricalStudent_preferred_countries',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
