# Generated by Django 6.0.6 on 2026-06-15 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicaluniversity",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical university",
                "verbose_name_plural": "historical Universities",
            },
        ),
        migrations.AlterModelOptions(
            name="university",
            options={"verbose_name_plural": "Universities"},
        ),
        migrations.AddField(
            model_name="historicaluniversity",
            name="scholarship_available",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="university",
            name="scholarship_available",
            field=models.BooleanField(default=False),
        ),
    ]
