# Generated by Django 5.2.15 on 2026-06-17 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_fix_historical_student"),
    ]

    operations = [
        # Remove history_user from HistoricalCountry before deleting the model
        migrations.RemoveField(
            model_name="historicalcountry",
            name="history_user",
        ),
        # Rename indexes
        migrations.RenameIndex(
            model_name="student",
            new_name="core_studen_nationa_53a2be_idx",
            old_name="core_studen_nationa_a978fd_idx",
        ),
        migrations.RenameIndex(
            model_name="university",
            new_name="core_univer_country_785b0a_idx",
            old_name="core_univer_country_4c3a85_idx",
        ),
        # Update HistoricalStudent fields with help_text
        migrations.AlterField(
            model_name="historicalstudent",
            name="_preferred_countries_json",
            field=models.JSONField(
                blank=True,
                default=list,
                editable=False,
                help_text="Internal: JSON backup of preferred countries",
            ),
        ),
        migrations.AlterField(
            model_name="historicalstudent",
            name="nationality",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Student's nationality",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="core.country",
            ),
        ),
        # Update HistoricalUniversity fields with help_text
        migrations.AlterField(
            model_name="historicaluniversity",
            name="country",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Select the country where the university is located",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="core.country",
            ),
        ),
        migrations.AlterField(
            model_name="historicaluniversity",
            name="data_source",
            field=models.CharField(
                choices=[
                    ("manual", "Manual Entry"),
                    ("ai_scraped", "AI Scraped"),
                    ("import", "Bulk Import"),
                ],
                default="manual",
                max_length=50,
            ),
        ),
        # Update Student fields with help_text
        migrations.AlterField(
            model_name="student",
            name="_preferred_countries_json",
            field=models.JSONField(
                blank=True,
                default=list,
                editable=False,
                help_text="Internal: JSON backup of preferred countries",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="nationality",
            field=models.ForeignKey(
                blank=True,
                help_text="Student's nationality",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="students_nationality",
                to="core.country",
            ),
        ),
        # Update University fields with help_text
        migrations.AlterField(
            model_name="university",
            name="country",
            field=models.ForeignKey(
                blank=True,
                help_text="Select the country where the university is located",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="universities",
                to="core.country",
            ),
        ),
        # Delete HistoricalCountry model (no longer needed)
        migrations.DeleteModel(
            name="HistoricalCountry",
        ),
    ]
